apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks
spec:
  selector:
    matchLabels:
      app: tasks
  
  template:
    metadata:
      labels:
        app: tasks
    
    spec:
      containers:
      - name: tasks
        image: alvinsoo1993/tasks-service
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: tasksservice
spec:
  type: NodePort
  selector:
    app: tasks
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31556
